GameHub/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views
import regbackend
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^$', views.view_profile, name='profile'),
    url(r'^gametest/', include('gametest.urls', namespace='gametest')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^accounts/register/$', regbackend.MyRegistrationView.as_view(), name='registration_register'),
    url(r'^groups/', include('groups.urls')),
    url(r'^userpage/', include('userpage.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gametest/urls.py
from django.conf.urls import url

from . import views

app_name = 'gametest'

# (0-9)+ or (?P<pk>\d+)
urlpatterns = [
	url(r'^mine/$', views.my_games, name='my_games'),
	url(r'^$', views.games_list, name='games_list'),
	url(r'^show/([0-9]+)$', views.game_details, name='game_details'),
	url(r'^create/$', views.manage_game, name='create_game'),
	url(r'^edit/(?P<id>\d+)$', views.manage_game, name='edit_game'),
	url(r'^user_list/(?P<id>\d+)$', views.user_list_game, name='user_list_game')
]

groups/urls.py
from django.conf.urls import url
from . import views
from .models import Group, UserGroup, Instances, Blogpost
from django.core.urlresolvers import reverse, reverse_lazy

app_name = 'groups'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'(?P<pk>[0-9]+)/$', views.GroupDetail.as_view(), name='detail'),
    url(r'^create/$', views.GroupCreate.as_view(), name='create'),
    url(r'^(?P<group_id>[0-9]+)/join/$', views.JoinGroup.as_view(), name='join'),

    url(r'^instance/(?P<instance_id>[0-9]+)$', views.InstanceDetails.as_view(), name='InstanceDetails'),
    url(r'^(?P<group_id>[0-9]+)/createInstanceGroup/$', views.GroupCreate.as_view(), name='CreateInstanceGr'),
    url(r'^(?P<group_id>[0-9]+)/LinkToGroup/$', views.CreateInstance.as_view(), name='CreateInstance'),
    url(r'^(?P<group_id>[0-9]+)/instances/$', views.GroupInstances, name='GroupInstances'),
    # url(r'^join/instance$', views.JoinInstance.as_view(), name='JoinInstance'),

    url(r'^(?P<group_id>[0-9]+)/createBlogpost/$', views.CreateBlogpost.as_view(), name='CreateBlogpost'),
    url(r'^blogpost/(?P<bp_id>[0-9]+)$', views.BlogpostDetails.as_view(), name='BlogpostDetails'),
    url(r'^(?P<group_id>[0-9]+)/blogposts/$', views.GroupBlogposts, name='GroupBlogposts'),
    # url(r'^(?P<group_id>[0-9]+)/blogposts/all', views.GroupBlogpostsAll.as_view(), name='GroupBlogpostsAll'),
]

userpage/urls.py
from django.conf.urls import url
from . import views

app_name = 'userpage'

urlpatterns = [
    url(r'^(?P<user_id>[0-9]+)/$', views.index, name='index'),
    url(r'^$', views.dashboard, name='dashboard')
]

GameHub/models.py
from django.db import models
from django.contrib.auth.models import User
from django_countries.fields import CountryField


class UserProfile(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    username = models.CharField(max_length=20, unique=True)
    #email = models.EmailField(max_length=20, unique=True)
    country = CountryField()
    user = models.OneToOneField(User)


    def __unicode__(self):
        return self.email

testSchema/models.py
from __future__ import unicode_literals

from django.db import models

class Blogpost(models.Model):
    text = models.TextField(db_column='Text')  # Field name made lowercase.
    bp_time = models.DateTimeField(db_column='BP_Time')  # Field name made lowercase.
    is_public = models.IntegerField(db_column='Is_public')  # Field name made lowercase. Field renamed to remove unsuitable characters.
    post_id = models.AutoField(primary_key=True, db_column='POST_ID')  # Field name made lowercase.
    group = models.ForeignKey('Group', related_name= 'group', db_column='GROUP_ID')  # Field name made lowercase.
    user = models.ForeignKey('User', models.DO_NOTHING, db_column='USER_ID')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'BLOGPOST'
        unique_together = (('post_id', 'group', 'user'),)


class BoardGame(models.Model):
    pieces = models.CharField(db_column='Pieces', max_length=20, blank=True, null=True)  # Field name made lowercase.
    game = models.ForeignKey('Game', models.DO_NOTHING, db_column='GAME_ID', primary_key=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'BOARD_GAME'


class CardGame(models.Model):
    cards_type = models.CharField(db_column='Cards_type', max_length=20, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    game = models.ForeignKey('Game', models.DO_NOTHING, db_column='GAME_ID', primary_key=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'CARD_GAME'


class ChatChannel(models.Model):
    cc_name = models.CharField(db_column='CC_Name', max_length=20)  # Field name made lowercase.
    group = models.ForeignKey('Group', models.DO_NOTHING, db_column='GROUP_ID')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'CHAT_CHANNEL'
        unique_together = (('cc_name', 'group'),)


class ChatMessage(models.Model):
    text = models.TextField(db_column='Text')  # Field name made lowercase.
    cm_time = models.DateTimeField(db_column='CM_Time')  # Field name made lowercase.
    cm_id = models.AutoField(primary_key=True, db_column='CM_ID')  # Field name made lowercase.
    user = models.ForeignKey('User', related_name='user', db_column='USER_ID')  # Field name made lowercase.
    cc_name = models.ForeignKey(ChatChannel, related_name='chat_cc_name', db_column='CC_Name')  # Field name made lowercase.
    group = models.ForeignKey(ChatChannel, related_name='chat_group', db_column='GROUP_ID')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'CHAT_MESSAGE'
        unique_together = (('cm_id', 'user', 'cc_name', 'group'),)


class Comments(models.Model):
    text = models.TextField(db_column='Text')  # Field name made lowercase.
    c_time = models.DateTimeField(db_column='C_Time')  # Field name made lowercase.
    c_id = models.AutoField(primary_key=True, db_column='C_ID')  # Field name made lowercase.
    commentor = models.ForeignKey('User', models.DO_NOTHING, db_column='COMMENTOR_ID')  # Field name made lowercase.
    post = models.ForeignKey(Blogpost, related_name='comment_post', db_column='POST_ID')  # Field name made lowercase.
    group = models.ForeignKey(Blogpost, related_name='comment_group', db_column='GROUP_ID')  # Field name made lowercase.
    post_writer = models.ForeignKey(Blogpost, related_name='comment_post_writer', db_column='POST_WRITER_ID')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'COMMENTS'
        unique_together = (('c_id', 'commentor', 'post', 'group', 'post_writer'),)


class Game(models.Model):
    game_id = models.AutoField(primary_key=True, db_column='GAME_ID')  # Field name made lowercase.
    name = models.CharField(db_column='Name', max_length=20)  # Field name made lowercase.
    description = models.TextField(db_column='Description', blank=True, null=True)  # Field name made lowercase.
    poster = models.TextField(db_column='Poster', blank=True, null=True)  # Field name made lowercase.
    no_of_players = models.CharField(db_column='No_of_players', max_length=20, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    duration = models.IntegerField(db_column='Duration', blank=True, null=True)  # Field name made lowercase.
    no_of_sessions = models.CharField(db_column='No_of_sessions', max_length=20, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    age_group = models.CharField(db_column='Age_group', max_length=20, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    competitve_level = models.CharField(db_column='Competitve_level', max_length=20, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.

    class Meta:
        managed = False
        db_table = 'GAME'


class Group(models.Model):
    group_id = models.AutoField(db_column='GROUP_ID', primary_key=True)  # Field name made lowercase.
    name = models.CharField(db_column='Name', max_length=20)  # Field name made lowercase.
    description = models.TextField(db_column='Description', blank=True, null=True)  # Field name made lowercase.
    area = models.CharField(db_column='Area', max_length=20)  # Field name made lowercase.
    is_public = models.IntegerField(db_column='Is_public')  # Field name made lowercase. Field renamed to remove unsuitable characters.
    creator = models.ForeignKey('User', models.DO_NOTHING, db_column='CREATOR_ID', blank=True,
                                null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'GROUPS'


class Instances(models.Model):
    time = models.DateTimeField(db_column='Time')  # Field name made lowercase.
    date = models.DateField(db_column='Date')  # Field name made lowercase.
    instance_location = models.CharField(db_column='INSTANCE_Location', max_length=20)  # Field name made lowercase.
    group = models.ForeignKey(Group, models.DO_NOTHING, db_column='GROUP_ID')  # Field name made lowercase.
    game = models.ForeignKey(Game, models.DO_NOTHING, db_column='GAME_ID', blank=True, null=True)  # Field name made lowercase.
    instance = models.ForeignKey(Group, related_name='instances_instance', db_column='INSTANCE_ID', primary_key=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'INSTANCES'
        unique_together = (('group', 'instance'),)


class List(models.Model):
    id = models.AutoField(primary_key=True, db_column='ID') # Surrogate key for django
    note = models.CharField(db_column='Note', max_length=20, blank=True, null=True)  # Field name made lowercase.
    ownership = models.IntegerField(db_column='Ownership')  # Field name made lowercase.
    skill = models.CharField(db_column='Skill', max_length=20, blank=True, null=True)  # Field name made lowercase.
    game = models.ForeignKey(Game, models.DO_NOTHING, db_column='GAME_ID')  # Field name made lowercase.
    user = models.ForeignKey('User', models.DO_NOTHING, db_column='USER_ID')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'LIST'
        unique_together = (('game', 'user'),)


class PhysicalGame(models.Model):
    physical_requirements = models.TextField(db_column='Physical_requirements', blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    game = models.ForeignKey(Game, models.DO_NOTHING, db_column='GAME_ID', primary_key=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'PHYSICAL_GAME'


class Platform(models.Model):
    id = models.AutoField(primary_key=True, db_column='ID') # Surrogate key for django
    os = models.CharField(db_column='OS', max_length=20)  # Field name made lowercase.
    game = models.ForeignKey('VideoGame', models.DO_NOTHING, db_column='GAME_ID')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'PLATFORM'
        unique_together = (('game', 'os'),)


class Report(models.Model):
    report_id = models.AutoField(primary_key=True, db_column='REPORT_ID')  # Field name made lowercase.
    type = models.CharField(db_column='Type', max_length=20, blank=True, null=True)  # Field name made lowercase.
    comment = models.TextField(db_column='Comment')  # Field name made lowercase.
    reporter = models.ForeignKey('User', related_name='reports_reporter',
                                 db_column='REPORTER_ID')  # Field name made lowercase.
    reported = models.ForeignKey('User', related_name='reported', db_column='REPORTED_ID')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'REPORTS'
        unique_together = (('report_id', 'reporter', 'reported'),)


class TabletopRpg(models.Model):
    narrative_authority = models.CharField(db_column='Narrative_authority', max_length=20, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    settings = models.TextField(db_column='Settings', blank=True, null=True)  # Field name made lowercase.
    style_of_play = models.CharField(db_column='Play_Style', max_length=20, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    components = models.CharField(db_column='Components', max_length=20, blank=True, null=True)  # Field name made lowercase.
    game = models.ForeignKey(Game, models.DO_NOTHING, db_column='GAME_ID', primary_key=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'TABLETOP_RPG'


class Tag(models.Model):
    id = models.AutoField(primary_key=True, db_column='ID') # Surrogate key for django

GameHub/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from registration.forms import RegistrationFormUniqueEmail
from .models import UserProfile

class LogInForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class UserProfileRegistrationForm(RegistrationFormUniqueEmail):

    class Meta:
        model = UserProfile
        fields = ['first_name', 'last_name', 'username', 'country', 'email', 'password1', 'password2']

GameHub/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse, reverse_lazy
from userpage import views

def view_profile(request):
    return redirect("/userpage/")

GameHub/templates/gametest/base.html
{% extends 'base.html' %}

{% block title %}Games Directory{% endblock %}

{% block nav %}
{{ block.super }}
<a class='button1' href='{% url 'gametest:games_list' %}'>All Games</a>
<a class='button1 red' href='{% url 'gametest:my_games' %}'>My Games</a>
{% endblock %}

GameHub/templates/gametest/game_details.html
{% extends "gametest/base.html" %}

{% block title %}Game Details{% endblock %}

{% block content %}

<h2>Game</h2>

{% for field in game_form %}
	<p class='note'>
		<b>{{ field.label }}:</b>
		{{ field.value|default_if_none:'-' }}
	</p>
{% endfor %}

<p class="note">
	<b>Genre:</b>
	{% for genre in genres %}
		{{ genre }}, 
	{% endfor %}
</p>


{% for form in gametypes_forms %}
	<h3>{{ form.instance.type }}</h3>
	<p class='note'>
		{% for field in form %}
			<b>{{ field.label }}:</b>
			{{ field.value|default_if_none:'-' }}
		{% endfor %}
	</p>
{% endfor %}

<h3>Players</h3>
{% if players_list %}
	<ol class='rounded-list'>
		{% for item in players_list %}
			<li><a href="{% url 'userpage:index' item.pk %}">{{ item.user }}</a></li>
			<ol>
				<li><b>Ownership:</b> {{ item.ownership }}</li>
				<li><b>Skill:</b> {{ item.skill }}</li>
				<li><b>Note:</b> {{ item.note }}</li>
			</ol>
		{% endfor %}
	</ol>
{% else %}
	no players
{% endif %}
{% endblock %}

GameHub/templates/gametest/game_form.html
{% extends "gametest/base.html" %}

{% block title %}Create Game{% endblock %}

{% block content %}
<form method='POST'>
	{% csrf_token %} <!-- some verification thing  -->
	<table id='game'>
		<h1>Game</h1>
		{{ game_form }}
	</table>
	<table id='genres'>
		<tr><td><h3>Genres</h3></td></tr>
		<tr><td><a href="javascript:void(0)" id="add_genre">Add Genre</a></td></tr>
		{{ genres_formset.management_form }}
		{% for form in genres_formset %}
			{{ form }}
		{% endfor %}
	</table>
	<table id='types'>
		{% for gametype_formset in gametypes_formsets %}
			{{ gametype_formset.management_form }}
			<tr><td><h2>{{ gametype_formset.model.type }}</h2></td></tr>
			{% for form in gametype_formset.forms %}
				{{ form }}
			{% endfor %}
		{% endfor %}
	</table>
	<input type='submit' value='Save'>
</form>

<script>
	var form_count = {{genres_formset.total_form_count}};
	$('#add_genre').click(function() {
		form_count++;
		var form = '{{genres_formset.empty_form|escapejs}}'.replace(/__prefix__/g, form_count-1);
		$('#genres').append(form)
		$('#id_type-TOTAL_FORMS').val(form_count);
	});
</script>
{% endblock %}

GameHub/templates/gametest/games_list.html
<style>
	body {
		width:80% !important;
	}
</style>
{% extends "gametest/base.html" %}
{% block title %}Game List{% endblock %}

{% block content %}
<table class='list'>
	<thread>
		{% for field in search_form %}
			<th>{{ field.label }}</th>
		{% endfor %}
		<th></th>
	</thread>
	<tbody>
		<tr>
			<form method='POST'>
			{% csrf_token %}
			{% for field in search_form %}
				<td>{{ field }}</td>
			{% endfor %}
				<td><input type='submit' value='Search'></td>
			</form>
		</tr>
		{% for game_form in forms_list %}
			<tr>
			{% for field in game_form %}
				<td>
					{% if field.label == 'Name' %}
						<a href='{% url 'gametest:game_details' game_form.instance.game_id %}'>{{ field.value }}</a>
					{% else %}
						{{ field.value|default_if_none:'-' }}</td>
					{% endif %}
			{% endfor %}
			<td>
				<a href='{% url 'gametest:edit_game' game_form.instance.game_id %}'>[edit] </a>
				<a href='{% url 'gametest:user_list_game' game_form.instance.game_id %}'>[add] </a>
			</td>
			</tr>
		{% empty %}
			No games exist
		{% endfor %}
	</tbody>
</table>

	
<a class='button2' href='{% url 'gametest:create_game' %}'>Create Game</a>
{% endblock %}

GameHub/templates/gametest/user_list_form.html
{% extends "gametest/base.html" %}

{% block title %}Create Game{% endblock %}

{% block content %}
<form method='POST'>
	{% csrf_token %} <!-- some verification thing  -->
	<table>
		<h1>Add Game</h1>
		{{ list_form }}
	</table>
	<input type='submit' value='Save'>
</form>
{% endblock %}