GameHub/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views
import regbackend
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^$', views.view_profile, name='profile'),
    url(r'^gametest/', include('gametest.urls', namespace='gametest')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^accounts/register/$', regbackend.MyRegistrationView.as_view(), name='registration_register'),
    url(r'^groups/', include('groups.urls')),
    url(r'^userpage/', include('userpage.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

groups/urls.py
from django.conf.urls import url
from . import views
from .models import Group, UserGroup, Instances, Blogpost
from django.core.urlresolvers import reverse, reverse_lazy

app_name = 'groups'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'(?P<pk>[0-9]+)/$', views.GroupDetail.as_view(), name='detail'),
    url(r'^create/$', views.GroupCreate.as_view(), name='create'),
    url(r'^(?P<group_id>[0-9]+)/join/$', views.JoinGroup.as_view(), name='join'),

    url(r'^instance/(?P<instance_id>[0-9]+)$', views.InstanceDetails.as_view(), name='InstanceDetails'),
    url(r'^(?P<group_id>[0-9]+)/createInstanceGroup/$', views.GroupCreate.as_view(), name='CreateInstanceGr'),
    url(r'^(?P<group_id>[0-9]+)/LinkToGroup/$', views.CreateInstance.as_view(), name='CreateInstance'),
    url(r'^(?P<group_id>[0-9]+)/instances/$', views.GroupInstances, name='GroupInstances'),
    # url(r'^join/instance$', views.JoinInstance.as_view(), name='JoinInstance'),

    url(r'^(?P<group_id>[0-9]+)/createBlogpost/$', views.CreateBlogpost.as_view(), name='CreateBlogpost'),
    url(r'^blogpost/(?P<bp_id>[0-9]+)$', views.BlogpostDetails.as_view(), name='BlogpostDetails'),
    url(r'^(?P<group_id>[0-9]+)/blogposts/$', views.GroupBlogposts, name='GroupBlogposts'),
    # url(r'^(?P<group_id>[0-9]+)/blogposts/all', views.GroupBlogpostsAll.as_view(), name='GroupBlogpostsAll'),
]

userpage/urls.py
from django.conf.urls import url
from . import views

app_name = 'userpage'

urlpatterns = [
    url(r'^(?P<user_id>[0-9]+)/$', views.index, name='index'),
    url(r'^$', views.dashboard, name='dashboard')
]

GameHub/models.py
from django.db import models
from django.contrib.auth.models import User
from django_countries.fields import CountryField


class UserProfile(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    username = models.CharField(max_length=20, unique=True)
    #email = models.EmailField(max_length=20, unique=True)
    country = CountryField()
    user = models.OneToOneField(User)


    def __unicode__(self):
        return self.email

GameHub/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from registration.forms import RegistrationFormUniqueEmail
from .models import UserProfile

class LogInForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class UserProfileRegistrationForm(RegistrationFormUniqueEmail):

    class Meta:
        model = UserProfile
        fields = ['first_name', 'last_name', 'username', 'country', 'email', 'password1', 'password2']

GameHub/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse, reverse_lazy
from userpage import views

def view_profile(request):
    return redirect("/userpage/")

GameHub/templates/base.html
<!DOCTYPE html>
<html>

<head>
{% comment %}

	<title>{% block title %}GameHub{% endblock %}</title>
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
{% endcomment %}
    <style>
		/*
		* PSDchat - Simple Flat Buttons
		* Author & Copyright (c) 2013: Marijan Petrovski
		* http://http://www.psdchat.com/
		* Support: IE8+
		*
		*/

		a, a:link, a:active, a:visited, a:hover {
			text-decoration: none;
			outline: none;
			}

		body {
			background: #ffffff;
			color: #00000;
			font-family: 'Open Sans', sans-serif;
			font-size: 15px;
			font-weight: normal;
			margin: 40px auto;
			width: 60%;
			}

		h1 {
			color: #34495e;
			font-family: 'Asap', sans-serif;
			font-size: 20px;
			font-weight: normal;
			margin: 0 23px 23px 0;
			}

		footer {
			font-size: 12px;
			color: grey;
			padding: 5px;
			text-align: center
			}

		nav {
		    margin-bottom: 5px;
		}

		/* Use the Following CSS Code for Button1*/

		.button1:link {
			padding: 13px 20px;
			background-color: #1abc9c;
			-moz-border-radius: 3px;
		    -webkit-border-radius: 3px;
		    -khtml-border-radius: 3px;
			border-radius: 3px;
			-moz-box-shadow: 0px 3px 0px 0px #029e81;
			-webkit-box-shadow: 0px 3px 0px 0px #029e81;
			box-shadow: 0px 3px 0px 0px #029e81;
			line-height: 100%;
			text-align: center;
			font-family: font-family: 'Open Sans', sans-serif;
			font-size: 12px;
			font-weight: 700;
			color: #ffffff;
			display: inline-block;
			cursor: pointer;
			}

		.button1:visited {
			background-color: #1abc9c;
			-moz-border-radius: 3px;
		    -webkit-border-radius: 3px;
		    -khtml-border-radius: 3px;
			border-radius: 3px;
			-moz-box-shadow: 0px 3px 0px 0px #029e81;
			-webkit-box-shadow: 0px 3px 0px 0px #029e81;
			box-shadow: 0px 3px 0px 0px #029e81;
			color: #ffffff;
			}

		.button1:hover {
			background-color: #81dac9;
			-moz-border-radius: 3px;
		    -webkit-border-radius: 3px;
		    -khtml-border-radius: 3px;
			border-radius: 3px;
			-moz-box-shadow: 0px 3px 0px 0px #78cfbf;
			-webkit-box-shadow: 0px 3px 0px 0px #78cfbf;
			box-shadow: 0px 3px 0px 0px #78cfbf;
			color: #ffffff;
			-webkit-transition: 0.5s;
			-moz-transition: 0.5s;
			-o-transition: 0.5s;
			transition: 0.5s;
			}

		.button1:active {
			background-color: #17a98c;
			-moz-border-radius: 3px;
		    -webkit-border-radius: 3px;
		    -khtml-border-radius: 3px;
			border-radius: 3px;
			-moz-box-shadow: 0px 3px 0px 0px #09977c;
			-webkit-box-shadow: 0px 3px 0px 0px #09977c;
			box-shadow: 0px 3px 0px 0px #09977c;
			}



		/* Use the Following CSS Code for Button2*/
		.button2:link {
			padding: 13px 20px;
			background-color: #8cc152;
			-moz-border-radius: 3px;
		    -webkit-border-radius: 3px;
		    -khtml-border-radius: 3px;
			border-radius: 3px;
			-moz-box-shadow: 0px 3px 0px 0px #7db046;
			-webkit-box-shadow: 0px 3px 0px 0px #7db046;
			box-shadow: 0px 3px 0px 0px #7db046;
			line-height: 100%;
			text-align: center;
			font-family: font-family: 'Open Sans', sans-serif;
			font-size: 12px;
			font-weight: 700;
			color: #ffffff;
			display: inline-block;
			cursor: pointer;
			}

		.button2:visited {
			background-color: #8cc152;
			-moz-border-radius: 3px;
		    -webkit-border-radius: 3px;
		    -khtml-border-radius: 3px;
			border-radius: 3px;
			-moz-box-shadow: 0px 3px 0px 0px #7db046;
			-webkit-box-shadow: 0px 3px 0px 0px #7db046;
			box-shadow: 0px 3px 0px 0px #7db046;
			color: #ffffff;
			}

		.button2:hover {
			background-color: #c0dd77;
			-moz-border-radius: 3px;
		    -webkit-border-radius: 3px;
		    -khtml-border-radius: 3px;
			border-radius: 3px;
			-moz-box-shadow: 0px 3px 0px 0px #bad76b;
			-webkit-box-shadow: 0px 3px 0px 0px #bad76b;
			box-shadow: 0px 3px 0px 0px #bad76b;
			color: #ffffff;
			-webkit-transition: 0.5s;
			-moz-transition: 0.5s;
			-o-transition: 0.5s;
			transition: 0.5s;
			}

		.button2:active {
			background-color: #85b74e;
			-moz-border-radius: 3px;
		    -webkit-border-radius: 3px;
		    -khtml-border-radius: 3px;
			border-radius: 3px;
			-moz-box-shadow: 0px 3px 0px 0px #7bad46;
			-webkit-box-shadow: 0px 3px 0px 0px #7bad46;
			box-shadow: 0px 3px 0px 0px #7bad46;
			}

		ol {
		    counter-reset: li; /* Initiate a counter */
		    list-style: none; /* Remove default numbering */
		    *list-style: decimal; /* Keep using default numbering for IE6/7 */
		    font: 15px 'trebuchet MS', 'lucida sans';
		    padding: 0;
		    margin-bottom: 4em;
		    text-shadow: 0 1px 0 rgba(255,255,255,.5);
		}

		ol ol {
		    margin: 0 0 0 2em; /* Add some left margin for inner lists */
		}

		/* -------------------------------------- */

		.rounded-list a{
			position: relative;
			display: block;
			padding: .4em .4em .4em 2em;
			*padding: .4em;
			margin: .5em 0;
			background: #ddd;
			color: #444;
			text-decoration: none;
			-moz-border-radius: .3em;
			-webkit-border-radius: .3em;
			border-radius: .3em;
			-webkit-transition: all .3s ease-out;
			-moz-transition: all .3s ease-out;
			-ms-transition: all .3s ease-out;
			-o-transition: all .3s ease-out;
			transition: all .3s ease-out;
		}

		.rounded-list a:hover{
			background: #eee;
		}

		.rounded-list a:hover:before{
			-moz-transform: rotate(360deg);
		  	-webkit-transform: rotate(360deg);
		    -moz-transform: rotate(360deg);
		    -ms-transform: rotate(360deg);
		    -o-transform: rotate(360deg);
		    transform: rotate(360deg);
		}

		.rounded-list a:before{
			content: counter(li);
			counter-increment: li;
			position: absolute;
			left: -1.3em;
			top: 50%;
			margin-top: -1.3em;
			background: #87ceeb;
			height: 2em;
			width: 2em;
			line-height: 2em;
			border: .3em solid #fff;
			text-align: center;
			font-weight: bold;
			-moz-border-radius: 2em;
			-webkit-border-radius: 2em;
			border-radius: 2em;
			-webkit-transition: all .3s ease-out;
			-moz-transition: all .3s ease-out;
			-ms-transition: all .3s ease-out;
			-o-transition: all .3s ease-out;
			transition: all .3s ease-out;
		}

		/* -------------------------------------- */

		.rectangle-list a{
			position: relative;
			display: block;
			padding: .4em .4em .4em .8em;
			*padding: .4em;
			margin: .5em 0 .5em 2.5em;
			background: #ddd;
			color: #444;
			text-decoration: none;
			-webkit-transition: all .3s ease-out;
			-moz-transition: all .3s ease-out;
			-ms-transition: all .3s ease-out;
			-o-transition: all .3s ease-out;
			transition: all .3s ease-out;
		}

		.rectangle-list a:hover{
			background: #eee;
		}

		.rectangle-list a:before{
			content: counter(li);
			counter-increment: li;
			position: absolute;
			left: -2.5em;
			top: 50%;
			margin-top: -1em;
			background: #fa8072;
			height: 2em;
			width: 2em;
			line-height: 2em;
			text-align: center;
			font-weight: bold;
		}

		.rectangle-list a:after{
			position: absolute;
			content: '';
			border: .5em solid transparent;
			left: -1em;
			top: 50%;
			margin-top: -.5em;
			-webkit-transition: all .3s ease-out;
			-moz-transition: all .3s ease-out;
			-ms-transition: all .3s ease-out;
			-o-transition: all .3s ease-out;
			transition: all .3s ease-out;
		}

		.rectangle-list a:hover:after{
			left: -.5em;
			border-left-color: #fa8072;
		}

		/* -------------------------------------- */

		.circle-list li{
		    padding: 2.5em;
		    border-bottom: 1px dashed #ccc;
		}

		.circle-list h2{
		    position: relative;
		    margin: 0;
		}

		.circle-list p{
		    margin: 0;
		}

		.circle-list h2:before{
		    content: counter(li);
		    counter-increment: li;
		    position: absolute;
		    z-index: -1;
		    left: -1.3em;
		    top: -.8em;
		    background: #f5f5f5;
		    height: 1.5em;
		    width: 1.5em;
		    border: .1em solid rgba(0,0,0,.05);
		    text-align: center;
		    font: italic bold 1em/1.5em Georgia, Serif;
		    color: #ccc;
		    -moz-border-radius: 1.5em;
		    -webkit-border-radius: 1.5em;
		    border-radius: 1.5em;
		    -webkit-transition: all .2s ease-out;
		    -moz-transition: all .2s ease-out;
		    -ms-transition: all .2s ease-out;
		    -o-transition: all .2s ease-out;
		    transition: all .2s ease-out;
		}

		.circle-list li:hover h2:before{
		    background-color: #ffd797;
		    border-color: rgba(0,0,0,.08);
		    border-width: .2em;
		    color: #444;
		    -webkit-transform: scale(1.5);
		    -moz-transform: scale(1.5);
		    -ms-transform: scale(1.5);
		    -o-transform: scale(1.5);
		    transform: scale(1.5);
				}

	.note,
    p.note {
    	vertical-align: top;
    	display: block;
    	color: #000000;
    	border: solid 1px #ffffff;
    	background-color: #ddd;
	    -moz-border-radius: 6px;
		-webkit-border-radius: 6px;
	    border-radius: 6px;
    	padding: 11px 20px;
	    mc-auto-number-format: '{b}Note: {/b}';
	}

	form{
	    max-width: 80%;
	    margin: 0 auto;
	    padding: 55px;
	    box-sizing: border-box;

	    background-color:  #ffffff;
	    box-shadow: 0 1px 8px 3px rgba(0, 0, 0, 0.1);

	    font: bold 14px sans-serif;
	    text-align: center;
	}

	form .required,
	form tr,
	form .form-row{
	    text-align: left;
	    margin-bottom: 22px;
	}

	/* The form title */

	form h1{
	    display: inline-block;
	    box-sizing: border-box;
	    color:  #4c565e;
	    font-size: 24px;
	    padding: 0 10px 15px;
	    border-bottom: 2px solid #6caee0;
	    margin: 0;
	}


	form .form-title-row{
	    text-align: center;
	    margin-bottom: 55px;
	}

	form h2{
	    text-align: center;
		margin-bottom: 5px;
		margin-top: 20px;
	}

	form h3,
	form .form-subtitle-row{
		text-align: center;
		margin-bottom: 10px;
		margin-top: 15px;
	}

	form tr label,
	form .form-row > label span{
	    display: inline-block;
	    box-sizing: border-box;
	    color: #5F5F5F;
	    width: 180px;
	    text-align: right;
	    vertical-align: top;
	    padding: 12px 25px;
	}

	form a {
	    display: inline-block;
	    box-sizing: border-box;
	    width: 180px;
	    text-align: right;
	    vertical-align: top;
	    padding: 12px 25px;
	}

	form input{
	    color:  #5f5f5f;
	    box-sizing: border-box;
	    width: 240px;
	    box-shadow: 1px 2px 4px 0 rgba(0, 0, 0, 0.08);
	    padding: 12px;
	    border: 1px solid #dbdbdb;
	}

	form input[type=radio],
	form input[type=checkbox]{
	    box-shadow: none;
	    width: auto;
	}

	form input[type=checkbox]{
	    margin-top: 13px;
	}

	form select{
	    background-color: #ffffff;
	    color:  #5f5f5f;
	    box-sizing: border-box;
	    max-width: 240px;
	    box-shadow: 1px 2px 4px 0 rgba(0, 0, 0, 0.08);
	    padding: 12px 8px;
	    border: 1px solid #dbdbdb;
	}

	form textarea{
	    color:  #5f5f5f;
	    box-sizing: border-box;
	    width: 240px;
	    height: 80px;
	    box-shadow: 1px 2px 4px 0 rgba(0, 0, 0, 0.08);
	    font: normal 13px sans-serif;
	    padding: 12px;
	    border: 1px solid #dbdbdb;
	    resize: vertical;
	}

	form .form-radio-buttons{
	    display: inline-block;
	    vertical-align: top;
	}

	form .form-radio-buttons > div{
	    margin-top: 10px;
	}

	form .form-radio-buttons label span{
	    margin-left: 8px;
	    color: #5f5f5f;
	    font-weight: normal;
	}

	form .form-radio-buttons input{
	    width: auto;
	}

	form input[type="submit"],
	form button{
	    display: block;
	    border-radius: 2px;
	    background-color:  #6caee0;
	    color: #ffffff;
	    font-weight: bold;
	    box-shadow: 1px 2px 4px 0 rgba(0, 0, 0, 0.08);
	    padding: 14px 22px;
	    border: 0;
	    margin: 40px 183px 0;
	}

	.list td:nth-child(even) {
		background-color: white,
	}

	.list td:last-child {
		background-color:  #f2f2f2;
	}

	.list th {
		background-color: #C3C3C3;
	}

	.list {
		width: 100px;
	}

	.list tr:hover {
		background-color: #f5f5f5
	}

	.red {
		color: red !important;
	}

	</style>

	<!-- jQuery -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>
</head>

<body>
	<header>
		{% block header %}<h1>GameHub</h1>{% endblock %}
	</header>
	<nav>
		{% block nav %}<a class='button1' href='{% url 'userpage:dashboard' %}'>Dashboard</a>{% endblock %}
	</nav>
    <br>
	<main>
		{% block content %}Main block | Override me :D{% endblock %}
	</main>
    <br>
	<footer>
		{% block footer %}ICS324 DB Project. Code: <a href='https://github.com/OmarWKH/324-gamehub'>https://github.com/OmarWKH/324-gamehub</a>{% endblock %}
	</footer>
</body>

</html>