GameHub/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views
import regbackend
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^$', views.view_profile, name='profile'),
    url(r'^gametest/', include('gametest.urls', namespace='gametest')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^accounts/register/$', regbackend.MyRegistrationView.as_view(), name='registration_register'),
    url(r'^groups/', include('groups.urls')),
    url(r'^userpage/', include('userpage.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gametest/urls.py
from django.conf.urls import url

from . import views

app_name = 'gametest'

# (0-9)+ or (?P<pk>\d+)
urlpatterns = [
	url(r'^mine/$', views.my_games, name='my_games'),
	url(r'^$', views.games_list, name='games_list'),
	url(r'^show/([0-9]+)$', views.game_details, name='game_details'),
	url(r'^create/$', views.manage_game, name='create_game'),
	url(r'^edit/(?P<id>\d+)$', views.manage_game, name='edit_game'),
	url(r'^user_list/(?P<id>\d+)$', views.user_list_game, name='user_list_game')
]

groups/urls.py
from django.conf.urls import url
from . import views
from .models import Group, UserGroup, Instances, Blogpost
from django.core.urlresolvers import reverse, reverse_lazy

app_name = 'groups'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'(?P<pk>[0-9]+)/$', views.GroupDetail.as_view(), name='detail'),
    url(r'^create/$', views.GroupCreate.as_view(), name='create'),
    url(r'^(?P<group_id>[0-9]+)/join/$', views.JoinGroup.as_view(), name='join'),

    url(r'^instance/(?P<instance_id>[0-9]+)$', views.InstanceDetails.as_view(), name='InstanceDetails'),
    url(r'^(?P<group_id>[0-9]+)/createInstanceGroup/$', views.GroupCreate.as_view(), name='CreateInstanceGr'),
    url(r'^(?P<group_id>[0-9]+)/LinkToGroup/$', views.CreateInstance.as_view(), name='CreateInstance'),
    url(r'^(?P<group_id>[0-9]+)/instances/$', views.GroupInstances, name='GroupInstances'),
    # url(r'^join/instance$', views.JoinInstance.as_view(), name='JoinInstance'),

    url(r'^(?P<group_id>[0-9]+)/createBlogpost/$', views.CreateBlogpost.as_view(), name='CreateBlogpost'),
    url(r'^blogpost/(?P<bp_id>[0-9]+)$', views.BlogpostDetails.as_view(), name='BlogpostDetails'),
    url(r'^(?P<group_id>[0-9]+)/blogposts/$', views.GroupBlogposts, name='GroupBlogposts'),
    # url(r'^(?P<group_id>[0-9]+)/blogposts/all', views.GroupBlogpostsAll.as_view(), name='GroupBlogpostsAll'),
]

userpage/urls.py
from django.conf.urls import url
from . import views

app_name = 'userpage'

urlpatterns = [
    url(r'^(?P<user_id>[0-9]+)/$', views.index, name='index'),
    url(r'^$', views.dashboard, name='dashboard')
]

GameHub/models.py
from django.db import models
from django.contrib.auth.models import User
from django_countries.fields import CountryField


class UserProfile(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    username = models.CharField(max_length=20, unique=True)
    #email = models.EmailField(max_length=20, unique=True)
    country = CountryField()
    user = models.OneToOneField(User)


    def __unicode__(self):
        return self.email

groups/models.py
from __future__ import unicode_literals
from django.db import models
from django.core.urlresolvers import reverse
from django.conf import settings
from gametest.models import Game

class Group(models.Model):
    group_id = models.AutoField(db_column='GROUP_ID', primary_key=True)  # Field name made lowercase.
    name = models.CharField(db_column='Name', max_length=20)  # Field name made lowercase.
    description = models.TextField(db_column='Description', blank=True, null=True)  # Field name made lowercase.
    area = models.CharField(db_column='Area', max_length=20)  # Field name made lowercase.
    is_public = models.IntegerField(db_column='Is_public')  # Field name made lowercase. Field renamed to remove unsuitable characters.
    creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,)

    class Meta:
        managed = False
        db_table = 'GROUPS'

    def __str__(self):
        return str(self.group_id)

    def __unicode__(self):
        return str(self.name)


    def get_absolute_url(self):
        return reverse('groups:detail', kwargs={'pk': self.pk})

class UserGroup(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Surrogate key for django
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,)  # Field name made lowercase.
    group = models.ForeignKey(Group, models.DO_NOTHING, db_column='GROUP_ID')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'USERS_GROUPS'
        unique_together = (('user', 'group'),)

    def __str__(self):
        return self.group.name

class Instances(models.Model):
    time = models.DateTimeField(db_column='Time')  # Field name made lowercase.
    instance_location = models.CharField(db_column='INSTANCE_Location', max_length=20)  # Field name made lowercase.
    group = models.ForeignKey(Group, models.DO_NOTHING, db_column='GROUP_ID')  # Field name made lowercase.
    game = models.ForeignKey(Game, models.DO_NOTHING, db_column='GAME_ID', blank=True, null=True)  # Field name made lowercase.
    instance = models.ForeignKey(Group, related_name='instances_instance', db_column='INSTANCE_ID',
                                 primary_key=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'INSTANCES'
        unique_together = (('group', 'instance'),)

    def __str__(self):
        return self.group.name + ' - ' + self.game.name + ' - ' + self.instance_location

    def get_absolute_url(self):
        return reverse('groups:InstanceDetails', kwargs={'instance_id': self.pk})

class Blogpost(models.Model):
    text = models.TextField(db_column='Text')  # Field name made lowercase.
    bp_time = models.DateTimeField(db_column='BP_Time')  # Field name made lowercase.
    is_public = models.IntegerField(db_column='Is_public')  # Field name made lowercase. Field renamed to remove unsuitable characters.
    post_id = models.AutoField(db_column='POST_ID', primary_key=True)  # Field name made lowercase.
    group = models.ForeignKey('Group', related_name= 'group', db_column='GROUP_ID')  # Field name made lowercase.
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'BLOGPOST'
        unique_together = (('post_id', 'group', 'user'),)

    def __str__(self):
        return str(self.post_id) + ' - ' + self.group.name + ' - ' + str(self.user)

    def get_absolute_url(self):
        return reverse('groups:BlogpostDetails', kwargs={'bp_id': self.post_id})

GameHub/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from registration.forms import RegistrationFormUniqueEmail
from .models import UserProfile

class LogInForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class UserProfileRegistrationForm(RegistrationFormUniqueEmail):

    class Meta:
        model = UserProfile
        fields = ['first_name', 'last_name', 'username', 'country', 'email', 'password1', 'password2']

GameHub/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse, reverse_lazy
from userpage import views

def view_profile(request):
    return redirect("/userpage/")

groups/views.py
from django.shortcuts import render
from .models import Group, UserGroup, Instances, Blogpost
from gametest.models import Game, List
from django.contrib.auth.models import User
from django.shortcuts import redirect, render, get_object_or_404
from django.core.urlresolvers import reverse, reverse_lazy
from django.views import generic
from django.conf import settings
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden, Http404
from django.views.generic import CreateView, UpdateView, DetailView
from django.template import loader
import datetime


class IndexView(generic.ListView):
    template_name = 'groups/index.html'

    def get_queryset(self):
        return Group.objects.all()


class GroupDetail(generic.DetailView):
    model = Group
    template_name = 'groups/detail.html'


class GroupCreate(CreateView):
    model = Group
    fields = ['name', 'description', 'area', 'is_public', 'creator']

    def get_initial(self):
        return {'creator': self.request.user }

    def get_form(self, form_class):
        form = super(generic.CreateView, self).get_form(form_class)
        current_username = self.request.user.username
        form.fields['creator'].queryset = User.objects.filter(username=current_username)
        return form

class JoinGroup(CreateView):
    model = UserGroup
    template_name = 'groups/join.html'
    fields = ['user', 'group']

    def get_initial(self):
        return {'user': self.request.user,
                'group': self.kwargs['group_id']}

    def get_form(self, form_class):
        form = super(generic.CreateView, self).get_form(form_class)
        current_username = self.request.user.username
        form.fields['user'].queryset = User.objects.filter(username=current_username)
        return form

    success_url = reverse_lazy('groups:index')

class InstanceDetails(generic.DetailView):
    model = Instances
    pk_url_kwarg = "instance_id"
    template_name = 'groups/instance_detail.html'


class CreateInstanceGr(CreateView):

    model = Group
    fields = ['name', 'description', 'area', 'is_public', 'creator']

    def get_initial(self):
        return {'creator': self.request.user,
                }

    def get_form(self, form_class):
        form = super(generic.CreateView, self).get_form(form_class)
        current_username = self.request.user.username
        form.fields['creator'].queryset = User.objects.filter(username=current_username)
        return form




class CreateInstance(CreateView):

    model = Instances
    template_name = 'groups/createInstance.html'
    fields = ['group', 'instance', 'game', 'instance_location', 'time']

    def get_initial(self):
        # try:
        #     group = UserGroup.objects.get(user=self.request.user, group=self.kwargs['group_id'])
        # except:
        #     raise Http404
        now = datetime.datetime.now()

        return {'instance': self.kwargs['group_id'],
                'time': now.strftime("%Y-%m-%d %H:%M")}

    def get_form(self, form_class):
        form = super(generic.CreateView, self).get_form(form_class)
        x = UserGroup.objects.filter(user=self.request.user).values_list('group')
        y = List.objects.filter(user=self.request.user).values_list('game')
        form.fields['group'].queryset = Group.objects.filter(group_id__in=x)
        form.fields['instance'].queryset = Group.objects.filter(pk=self.kwargs['group_id'])
        form.fields['game'].queryset = Game.objects.filter(game_id__in=y)
        return form



class CreateBlogpost(CreateView):
    model = Blogpost
    template_name = 'groups/createBlogpost.html'
    fields = ['text', 'is_public', 'group', 'user', 'bp_time']

    def get_initial(self):
        # try:
        #     group = UserGroup.objects.get(user=self.request.user, group=self.kwargs['group_id'])
        # except:
        #     raise Http404

        now = datetime.datetime.now()
        return {'user': self.request.user,
                'group': self.kwargs['group_id'],
                'bp_time': now.strftime("%Y-%m-%d %H:%M")}


    def get_form(self, form_class):
        form = super(generic.CreateView, self).get_form(form_class)
        current_username = self.request.user.username
        x = UserGroup.objects.filter(user=self.request.user).values_list('group')
        form.fields['user'].queryset = User.objects.filter(username=current_username)
        form.fields['group'].queryset = Group.objects.filter(group_id__in=x)
        return form

class BlogpostDetails(DetailView):
    model = Blogpost
    pk_url_kwarg = "bp_id"
    template_name = 'groups/blogpost_detail.html'

def GroupBlogposts(request, group_id):
    group_id = int(group_id)
    gname = Group.objects.get(pk=group_id)
    all_bps = Blogpost.objects.all()
    template = loader.get_template('groups/blogpost_of_group.html')
    context = {
        'all_bps': all_bps,
        'group_id': group_id,
        'gname': gname,
    }

    return HttpResponse(template.render(context, request))

def GroupInstances(request, group_id):
    group_id = int(group_id)
    gname = Group.objects.get(pk=group_id)
    all_instances = Instances.objects.all()
    template = loader.get_template('groups/instance_of_group.html')
    context = {
        'all_instances': all_instances,
        'group_id': group_id,
        'gname': gname,
    }

    return HttpResponse(template.render(context, request))

GameHub/templates/groups/base.html
{% extends 'base.html' %}

{% block title %}Groups{% endblock %}

{% block nav %}
{{ block.super }}
<a class='button1' href='{% url 'groups:index' %}'>All Groups</a>
{% endblock %}

GameHub/templates/groups/blogpost_detail.html
{% extends "groups/base.html" %}

{% block content %}
<h1>Details of {{ blogpost.pk}}</h1>

<p class="note"><b>User:   </b>{{ blogpost.user }}</p>
<p class="note"><b>Group: </b><a href="{% url 'groups:detail' blogpost.group.pk %}"> {{ blogpost.group.name }}</a></p>
<p class="note"><b>Time: </b>{{ blogpost.bp_time }}</p>
<p class="note"><b>Text: </b><br>{{ blogpost.text | linebreaksbr }}</p>
{% endblock %}

GameHub/templates/groups/blogpost_of_group.html
{% extends "groups/base.html" %}

{% block content %}
<h1>Blogposts of {{ gname }}</h1>
<ol class="rounded-list">
{% for bp in all_bps %}
    {% if bp.group.pk == group_id %}
        <li><a href="{% url 'groups:BlogpostDetails' bp.pk %}">{{ bp.pk }} - {{ bp.group.name }} - {{ bp.user }}</a></li>
    {% endif %}
{% endfor %}
</ol>
{% endblock %}

GameHub/templates/groups/createBlogpost.html
{% extends 'groups/base.html' %}


{% block content %}

<form class="form-basic" action="" method="post" enctype="multipart/form-data">
    <div class="form-title-row">
    <h1>Create Blogpost</h1>
    </div>

    {% csrf_token %}
{% for field in form %}
     <div class="form-row">
    <span>{{ field.errors }}</span>

    <label>{{ field.label_tag }}</label>
    <div>{{ field }}</div>
</div>
{% endfor %}
<div class="form-row">
<button type="submit">Create</button>
</div>
</form>
{% endblock %}

GameHub/templates/groups/createInstance.html
{% extends 'base.html' %}

{% block content %}


<form class="form-basic" action="" method="post" enctype="multipart/form-data">
<div class="form-title-row">
    <h1>Create an Instance</h1>
</div>
    {% csrf_token %}
{% for field in form %}
    <div class="form-row">
    <span>{{ field.errors }}</span>

    <label>{{ field.label_tag }}</label>
    <div>{{ field }}</div>
    </div>
{% endfor %}
<div class="form-row">
<button type="submit">Create</button>
    </div>
</form>
{% endblock %}

GameHub/templates/groups/detail.html
{% extends "groups/base.html" %}

{% block content %}
<h1>Details of {{ group.name}}</h1>

<p class="note"><b>ID: </b> {{ group.pk }}</p>
<p class="note"><b>Creator: </b>{{ group.creator }}</p>
<p class="note"><b>Description: </b> {{ group.description }}</p>
<p class="note"><b>Location: </b>{{ group.area }}</p>
<br>
    <hr>
    <br>
    <br>
<b>Users Joined:</b>
<ol class="rounded-list">
{% for g in group.usergroup_set.all %}
    {% if g.group_id == group.pk %}
        <li><a href="{% url 'userpage:index' g.user.pk %}">{{ g.user }}</a></li>
    {% endif %}
{% endfor %}
</ol>
    <hr>
<br>
    <ol class="rectangle-list">
<li><a href="{% url 'groups:GroupInstances' group.pk %}">Instances</a></li>
<li><a href="{% url 'groups:CreateInstanceGr' group.pk %}">Create Instance</a></li>
<li><a href="{% url 'groups:GroupBlogposts' group.pk %}">Blogposts</a></li>
<li><a href="{% url 'groups:CreateBlogpost' group.pk %}">Create Blogpost</a></li>
        </ol>
<br>
<br>
<br>
<a class="button1" href="{% url 'groups:join' group.pk %}">JOIN</a>
<br>
    <br>
<a class="button2" href="{% url 'groups:CreateInstance' group.pk %}">Make it an instance</a>
{% endblock %}

GameHub/templates/groups/form-template.html
{% for field in form %}
    <div class="form-row">
    <span>{{ field.errors }}</span>

    <label>{{ field.label_tag }}</label>
    <div>{{ field }}</div>
    </div>
{% endfor %}

GameHub/templates/groups/group_form.html
{% extends "groups/base.html" %}

{% block content %}


<form class="form-basic" action="" method="post" enctype="multipart/form-data">
    <div class="form-title-row">
    <h1>Create a Group</h1>
    </div>
    {% csrf_token %}
{% include 'groups/form-template.html' %}
<div class="form-row">
<button type="submit">Create</button>
</div>
</form>
{% endblock %}

GameHub/templates/groups/index.html
{% extends "groups/base.html" %}

{% block content %}
<h1>List of Groups</h1>

    <div class="shadow">
<ol class="rounded-list">
    {% for group in object_list %}
        {% if group.is_public == 1 %}
        <li><a href="{{ group.group_id }}">{{ group.name }}</a></li>
        {% endif %}
    {% endfor %}
</ol>
</div>
<a class="button2" href="create/">Create a group</a>
{% endblock %}

GameHub/templates/groups/instance_detail.html
{% extends "groups/base.html" %}

{% block content %}
<h1>Details of {{ instances.instance }}</h1>

<p class="note"><b>ID: </b> {{ instances.instance.pk }}</p>
<p class="note"><b>Creator: </b> {{ instances.instance.creator }}</p>
<p class="note"><b>Description: </b> {{ instances.instance.description }}</p>
<p class="note"><b>Time: </b> {{ instances.time }}</p>
<p class="note"><b>Area: </b>{{ instances.group.area }}</p>
<p class="note"><b>Location: </b>{{ instances.instance_location }}</p>
<p class="note"><b>Group: </b><a href="{% url 'groups:detail' instances.instance.pk %}"> {{ instances.instance }}</a></p>
<p class="note"><b>Owner Group: </b><a href="{% url 'groups:detail' instances.group.pk %}">{{ instances.group.name }}</a></p>
<p class="note"><b>Game: </b><a href="{% url 'gametest:game_details' instances.game.pk %}">{{ instances.game.name }}</a></p>
{% endblock %}

GameHub/templates/groups/instance_of_group.html
{% extends "groups/base.html" %}

{% block content %}

<h1>Instances of {{ gname }}</h1>
<ol class="rounded-list">

{% for instance in all_instances %}
    {% if instance.group.pk == group_id %}
        <li><a href="{% url 'groups:InstanceDetails' instance.pk %}">{{ instance.instance.name }} - {{ instance.game.name }} - {{ instance.instance_location }}</a></li>
    {% endif %}
{% endfor %}

</ol>
{% endblock %}

GameHub/templates/groups/join.html
{% extends "groups/base.html" %}

{% block content %}


<form class="form-basic" action="" method="post" enctype="multipart/form-data">
{% csrf_token %}
   <div class="form-title-row">
   </div>
<h1>Join a Group</h1>
{% for field in form %}
    <div class="form-row">
    <span>{{ field.errors }}</span>

    <label>{{ field.label_tag }}</label>
    <div>{{ field }}</div>
    </div>
{% endfor %}
   <div class="form-row">
<button type="submit">Join</button>

       </div>
</form>
{% endblock %}