GameHub/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views
import regbackend
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^$', views.view_profile, name='profile'),
    url(r'^gametest/', include('gametest.urls', namespace='gametest')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^accounts/register/$', regbackend.MyRegistrationView.as_view(), name='registration_register'),
    url(r'^groups/', include('groups.urls')),
    url(r'^userpage/', include('userpage.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gametest/urls.py
from django.conf.urls import url

from . import views

app_name = 'gametest'

# (0-9)+ or (?P<pk>\d+)
urlpatterns = [
	url(r'^mine/$', views.my_games, name='my_games'),
	url(r'^$', views.games_list, name='games_list'),
	url(r'^show/([0-9]+)$', views.game_details, name='game_details'),
	url(r'^create/$', views.manage_game, name='create_game'),
	url(r'^edit/(?P<id>\d+)$', views.manage_game, name='edit_game'),
	url(r'^user_list/(?P<id>\d+)$', views.user_list_game, name='user_list_game')
]

groups/urls.py
from django.conf.urls import url
from . import views
from .models import Group, UserGroup, Instances, Blogpost
from django.core.urlresolvers import reverse, reverse_lazy

app_name = 'groups'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'(?P<pk>[0-9]+)/$', views.GroupDetail.as_view(), name='detail'),
    url(r'^create/$', views.GroupCreate.as_view(), name='create'),
    url(r'^(?P<group_id>[0-9]+)/join/$', views.JoinGroup.as_view(), name='join'),

    url(r'^instance/(?P<instance_id>[0-9]+)$', views.InstanceDetails.as_view(), name='InstanceDetails'),
    url(r'^(?P<group_id>[0-9]+)/createInstanceGroup/$', views.GroupCreate.as_view(), name='CreateInstanceGr'),
    url(r'^(?P<group_id>[0-9]+)/LinkToGroup/$', views.CreateInstance.as_view(), name='CreateInstance'),
    url(r'^(?P<group_id>[0-9]+)/instances/$', views.GroupInstances, name='GroupInstances'),
    # url(r'^join/instance$', views.JoinInstance.as_view(), name='JoinInstance'),

    url(r'^(?P<group_id>[0-9]+)/createBlogpost/$', views.CreateBlogpost.as_view(), name='CreateBlogpost'),
    url(r'^blogpost/(?P<bp_id>[0-9]+)$', views.BlogpostDetails.as_view(), name='BlogpostDetails'),
    url(r'^(?P<group_id>[0-9]+)/blogposts/$', views.GroupBlogposts, name='GroupBlogposts'),
    # url(r'^(?P<group_id>[0-9]+)/blogposts/all', views.GroupBlogpostsAll.as_view(), name='GroupBlogpostsAll'),
]

userpage/urls.py
from django.conf.urls import url
from . import views

app_name = 'userpage'

urlpatterns = [
    url(r'^(?P<user_id>[0-9]+)/$', views.index, name='index'),
    url(r'^$', views.dashboard, name='dashboard')
]

GameHub/models.py
from django.db import models
from django.contrib.auth.models import User
from django_countries.fields import CountryField


class UserProfile(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    username = models.CharField(max_length=20, unique=True)
    #email = models.EmailField(max_length=20, unique=True)
    country = CountryField()
    user = models.OneToOneField(User)


    def __unicode__(self):
        return self.email

userpage/models.py
from __future__ import unicode_literals
from django.db import models
from django.core.urlresolvers import reverse
from django.conf import settings

GameHub/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from registration.forms import RegistrationFormUniqueEmail
from .models import UserProfile

class LogInForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class UserProfileRegistrationForm(RegistrationFormUniqueEmail):

    class Meta:
        model = UserProfile
        fields = ['first_name', 'last_name', 'username', 'country', 'email', 'password1', 'password2']

GameHub/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse, reverse_lazy
from userpage import views

def view_profile(request):
    return redirect("/userpage/")

userpage/views.py
from groups.models import UserGroup, Group
from gametest.models import Game, List, Type
from django.contrib.auth.models import User
from django.conf import settings
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from random import randint



def index(request, user_id):
    user_id = int(user_id)
    uname = User.objects.get(pk=user_id)
    all_groups = UserGroup.objects.all()
    all_lists = List.objects.all()
    template = loader.get_template('userpage/index.html')
    context = {
        'all_groups': all_groups,
        'user_id': user_id,
        'all_lists': all_lists,
        'uname': uname,
    }
    return HttpResponse(template.render(context, request))


def dashboard(request):
    if request.user.is_anonymous():
        return HttpResponseRedirect(settings.LOGIN_URL)

    lst = []
    lst2 = []
    groups = Group.objects.all()
    all_lists = List.objects.all()
    all_games = Game.objects.all()
    all_types = Type.objects.all()
    template = loader.get_template('userpage/dashboard.html')

    # to find genres
    for gl in all_lists:
        if gl.user.id == request.user.pk:
            lst.append(gl.game.pk)

    for t in all_types:
        for g in lst:
            if g == t.game.game_id:
                lst2.append(t.genre)


    if len(lst) == 0 or len(lst2) == 0:
        context = {
            'groups': groups,
            'all_lists': all_lists,
            'all_games': all_games,
            'all_types': all_types,
        }
        return HttpResponse(template.render(context, request))

    clst2 = len(lst2)
    rand = randint(0, clst2-1)
    genre = lst2[rand]


    context = {
        'groups': groups,
        'all_lists': all_lists,
        'all_games': all_games,
        'all_types': all_types,
        'genre': genre,
    }

    return HttpResponse(template.render(context, request))

GameHub/templates/userpage/dashboard.html
{% extends "base.html" %}

{% block nav %}
    <a class="button1" href="{% url 'gametest:games_list' %}">Create/List Games</a> |
    <a class="button1" href="{% url 'groups:index' %}">List of groups</a> |
    <a class="button1" href="{% url 'groups:create' %}">Create Groups</a> |
    <a class="button1" href="{% url 'groups:join' 0%}">Join Groups</a> |
    <a class="button1" href="{% url 'gametest:games_list' %}">Find Games</a> |
     <a class="button1" href="{% url 'userpage:index' request.user.pk %}">Profile</a>
{% endblock %}
{% block content %}
<h1>Welcome {{ request.user }},</h1>

<h3>Games You May List</h3> <!-- Supposed to select game info arbitrary (type, genre, platform) and then show similar games (Change every time) -->
<ol class="rounded-list">
{% for type in all_types %}
    {% if genre == type.genre %}
        <li><a href="{% url 'gametest:user_list_game' type.game.pk %}">{{ type.game.name }}</a></li>
        <ol>
        <li><a href="{% url 'gametest:game_details' type.game.pk %}">Details</a></li>
        </ol>
    {% endif %}
{% endfor %}
</ol>
{% endblock %}

GameHub/templates/userpage/index.html
{% extends "base.html" %}

{% block content %}
<h1>Info About {{ uname }}</h1>

<h3>Groups {{ uname }} Joined: </h3>
    <ol class="rounded-list">
{% for group in all_groups %}
    {% if group.user.id == user_id %}
        <li><a href="{% url 'groups:index' %}{{ group.group.pk }}">{{ group.group }}</a></li>

    {% endif %}
{% endfor %}
</ol>
<hr>
    <br>
<h3>Games {{ uname }} Listed: </h3>
    <ol class="rounded-list">
{% for list in all_lists %}
    {% if list.user.id == user_id %}
        <li><a href="{% url 'gametest:game_details' list.game.pk %}">{{ list.game.name }}</a></li>
    {% endif %}
{% endfor %}
    </ol>
{% endblock %}